spec:
  template:
    spec:
      # Declare a volume mounting the config map
      volumes:
        - configMap:
            # Name of the config map
            name: disaster-simulator
            # Define the items from the config map to mount
            items:
              - key: app-config.properties
                path: app-config.properties
              - key: LNames.txt
                path: LNames.txt
              - key: FNames.txt
                path: FNames.txt
          name: config

      containers:
        - name: disaster-simulator
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: APP_CONFIGMAP_NAME
              value: disaster-simulator
            - name: APP_CONFIGMAP_KEY
              value: app-config.properties
          # Mount the volume define above in /deployments/config
          volumeMounts:
            - name: config
              mountPath: /deployments/config

